### ISSUE TITLE
(ArgumentError) "wrong number of arguments (given 0, expected 2)

### ISSUE THREAD

**Issue by fiedl** [fiedl/your_platform#23]
Some active job (sidekiq) workers for caching raise this error.

For example: http://support.wingolfsplattform.org/tickets/6930

### Trace

```
2017-04-07T22:27:24.926Z 12867 TID-otilwgclw WARN: {"class"=>"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper", "wrapped"=>"RenewCacheJob", "queue"=>"retry", "args"=>[{"job_class"=>"RenewCacheJob", "job_id"=>"08ce65dc-af62-4af3-a222-f71c58ec68f4", "queue_name"=>"retry", "arguments"=>[], "locale"=>"en"}], "retry"=>false, "backtrace"=>true, "jid"=>"b3dbe9255da3b2a74aa43c74", "created_at"=>1491604005.413566, "enqueued_at"=>1491604044.8760746}
```

Note: This is the **retry** queue. Apparently, there are no `arguments`, but there should be arguments for the `RenewCacheJob`.

```
2017-04-07T22:27:24.894Z 12867 TID-otilwgclw RenewCacheJob JID-b3dbe9255da3b2a74aa43c74 INFO: start
2017-04-07T22:27:24.894Z 12867 TID-otils1310 WARN: /var/wingolfsplattform/vendor/bundle/ruby/2.3.0/bundler/gems/your_platform-566e4bece7db/app/jobs/renew_cache_job.rb:12:in `perform'
/var/wingolfsplattform/vendor/bundle/ruby/2.3.0/gems/activejob-4.2.7.1/lib/active_job/execution.rb:32:in `block in perform_now'
/var/wingolfsplattform/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:117:in `call'
/var/wingolfsplattform/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
/var/wingolfsplattform/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:505:in `call'
/var/wingolfsplattform/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
/var/wingolfsplattform/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:343:in `block (2 levels) in simple'
/var/wingolfsplattform/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.0.325/lib/new_relic/agent/instrumentation/active_job.rb:46:in `perform'
/var/wingolfsplattform/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.0.325/lib/new_relic/agent/instrumentation/active_job.rb:20:in `block (3 levels) in <top (required)>'
/var/wingolfsplattform/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:441:in `instance_exec'
/var/wingolfsplattform/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:441:in `block in make_lambda'
/var/wingolfsplattform/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:342:in `block in simple'
/var/wingolfsplattform/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:497:in `block in around'
/var/wingolfsplattform/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:505:in `call'
/var/wingolfsplattform/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
/var/wingolfsplattform/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:343:in `block (2 levels) in simple'
/var/wingolfsplattform/vendor/bundle/ruby/2.3.0/gems/i18n-0.7.0/lib/i18n.rb:257:in `with_locale'
/var/wingolfsplattform/vendor/bundle/ruby/2.3.0/gems/activejob-4.2.7.1/lib/active_job/translation.rb:7:in `block (2 levels) in <module:Translation>'
/var/wingolfsplattform/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:441:in `instance_exec'
/var/wingolfsplattform/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:441:in `block in make_lambda'
/var/wingolfsplattform/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:342:in `block in simple'
/var/wingolfsplattform/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:497:in `block in around'
/var/wingolfsplattform/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:505:in `call'
/var/wingolfsplattform/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
/var/wingolfsplattform/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:343:in `block (2 levels) in simple'
/var/wingolfsplattform/vendor/bundle/ruby/2.3.0/gems/activejob-4.2.7.1/lib/active_job/logging.rb:23:in `block (4 levels) in <module:Logging>'
/var/wingolfsplattform/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:164:in `block in instrument'
/var/wingolfsplattform/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/var/wingolfsplattform/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:164:in `instrument'
/var/wingolfsplattform/vendor/bundle/ruby/2.3.0/gems/activejob-4.2.7.1/lib/active_job/logging.rb:22:in `block (3 levels) in <module:Logging>'
/var/wingolfsplattform/vendor/bundle/ruby/2.3.0/gems/activejob-4.2.7.1/lib/active_job/logging.rb:43:in `block in tag_logger'
/var/wingolfsplattform/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/tagged_logging.rb:68:in `block in tagged'
/var/wingolfsplattform/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/tagged_logging.rb:26:in `tagged'
/var/wingolfsplattform/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/tagged_logging.rb:68:in `tagged'
/var/wingolfsplattform/vendor/bundle/ruby/2.3.0/gems/activejob-4.2.7.1/lib/active_job/logging.rb:43:in `tag_logger'
/var/wingolfsplattform/vendor/bundle/ruby/2.3.0/gems/activejob-4.2.7.1/lib/active_job/logging.rb:19:in `block (2 levels) in <module:Logging>'
/var/wingolfsplattform/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:441:in `instance_exec'
/var/wingolfsplattform/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:441:in `block in make_lambda'
/var/wingolfsplattform/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:342:in `block in simple'
/var/wingolfsplattform/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:497:in `block in around'
/var/wingolfsplattform/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:505:in `call'
/var/wingolfsplattform/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/var/wingolfsplattform/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:778:in `_run_perform_callbacks'
/var/wingolfsplattform/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
/var/wingolfsplattform/vendor/bundle/ruby/2.3.0/gems/activejob-4.2.7.1/lib/active_job/execution.rb:31:in `perform_now'
/var/wingolfsplattform/vendor/bundle/ruby/2.3.0/gems/activejob-4.2.7.1/lib/active_job/execution.rb:21:in `execute'
/var/wingolfsplattform/vendor/bundle/ruby/2.3.0/gems/activejob-4.2.7.1/lib/active_job/queue_adapters/sidekiq_adapter.rb:42:in `perform'
/var/wingolfsplattform/vendor/bundle/ruby/2.3.0/gems/sidekiq-3.5.4/lib/sidekiq/processor.rb:80:in `execute_job'
/var/wingolfsplattform/vendor/bundle/ruby/2.3.0/gems/sidekiq-3.5.4/lib/sidekiq/processor.rb:56:in `block (2 levels) in process'
/var/wingolfsplattform/vendor/bundle/ruby/2.3.0/gems/sidekiq-3.5.4/lib/sidekiq/middleware/chain.rb:127:in `block in invoke'
/var/wingolfsplattform/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.0.325/lib/new_relic/agent/instrumentation/sidekiq.rb:33:in `block in call'
/var/wingolfsplattform/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.0.325/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:363:in `perform_action_with_newrelic_trace'
/var/wingolfsplattform/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.0.325/lib/new_relic/agent/instrumentation/sidekiq.rb:29:in `call'
/var/wingolfsplattform/vendor/bundle/ruby/2.3.0/gems/sidekiq-3.5.4/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/var/wingolfsplattform/vendor/bundle/ruby/2.3.0/gems/sidekiq-3.5.4/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
/var/wingolfsplattform/vendor/bundle/ruby/2.3.0/gems/sidekiq-3.5.4/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/var/wingolfsplattform/vendor/bundle/ruby/2.3.0/gems/sidekiq-3.5.4/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
/var/wingolfsplattform/vendor/bundle/ruby/2.3.0/gems/sidekiq-3.5.4/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/var/wingolfsplattform/vendor/bundle/ruby/2.3.0/gems/sidekiq-3.5.4/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
/var/wingolfsplattform/vendor/bundle/ruby/2.3.0/gems/sidekiq-3.5.4/lib/sidekiq/logging.rb:30:in `with_context'
/var/wingolfsplattform/vendor/bundle/ruby/2.3.0/gems/sidekiq-3.5.4/lib/sidekiq/middleware/server/logging.rb:7:in `call'
/var/wingolfsplattform/vendor/bundle/ruby/2.3.0/gems/sidekiq-3.5.4/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/var/wingolfsplattform/vendor/bundle/ruby/2.3.0/gems/sidekiq-3.5.4/lib/sidekiq/middleware/chain.rb:132:in `invoke'
/var/wingolfsplattform/vendor/bundle/ruby/2.3.0/gems/sidekiq-3.5.4/lib/sidekiq/processor.rb:51:in `block in process'
/var/wingolfsplattform/vendor/bundle/ruby/2.3.0/gems/sidekiq-3.5.4/lib/sidekiq/processor.rb:104:in `stats'
/var/wingolfsplattform/vendor/bundle/ruby/2.3.0/gems/sidekiq-3.5.4/lib/sidekiq/processor.rb:50:in `process'
/var/wingolfsplattform/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
/var/wingolfsplattform/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
/var/wingolfsplattform/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/async.rb:7:in `dispatch'
/var/wingolfsplattform/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
/var/wingolfsplattform/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
/var/wingolfsplattform/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
/var/wingolfsplattform/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
/var/wingolfsplattform/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
```

**Comment by fiedl** [comment]
This might be related to https://github.com/rails/rails/issues/22044, https://github.com/rails/rails/pull/26221 and be caused by an `ActiveJob::DeserializationError`, which will be risen when a record is not available to the background job after creation, yet. The strategy for this issue is to retry the job in a couple of seconds when the record should be available. But the deserialization of the arguments is not completed when this error is raised; thus the arguments are not passed to the `retry` queue.

**Comment by fiedl** [comment]
Possible fix: https://github.com/rails/rails/issues/22044#issuecomment-240997327

```ruby
class ApplicationJob < ActiveJob::Base
  rescue_from StandardError do |exception|
    ExceptionTrackingThingy.track(exception, job: serialize)
    raise exception
  end

  # @see https://github.com/rails/rails/issues/22044
  def serialize
    serialized = super

    # @see https://github.com/rails/rails/blob/v5.0.0.1/activejob/lib/active_job/core.rb#L116
    if defined?(@serialized_arguments) && @serialized_arguments.present?
      serialized["arguments"] = @serialized_arguments
    end

    serialized
  end
end
```

**Comment by fiedl** [comment]
This has resolved the issue.
